name: Docker

on:
  push:
    paths:
      - "Dockerfile"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build and publish to Docker Hub
        run: |
          docker buildx build --push \
            --tag fiction7799/dockarm:latest \
            --platform linux/arm64 .
